---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: dynatrace-service
  replicas: 1
  template:
    metadata:
      labels:
        run: dynatrace-service
    spec:
      serviceAccountName: keptn-dynatrace-service
      containers:
        - name: dynatrace-service
          image: keptncontrib/dynatrace-service:0.8.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: API_WEBSOCKET_URL
              value: 'ws://api-service:8080/websocket'
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: DATASTORE
              value: 'http://mongodb-datastore:8080'
            - name: PLATFORM
              value: kubernetes
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_API_TOKEN
            - name: DT_TENANT
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: DT_TENANT
            - name: KEPTN_API_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_URL
            - name: KEPTN_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_API_TOKEN
            - name: KEPTN_BRIDGE_URL
              valueFrom:
                secretKeyRef:
                  name: dynatrace
                  key: KEPTN_BRIDGE_URL
                  optional: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-service-distributor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:0.7.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: 'dynatrace-service'
      serviceAccountName: keptn-default