apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynatrace-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dynatrace-service.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dynatrace-service.selectorLabels" . | nindent 4 }}
